# analysis_options.yaml
include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    unused_import: warning
    dead_code: warning
    unused_element: ignore

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_print: false
    prefer_final_fields: true
    always_specify_types: true
    annotate_overrides: true
    camel_case_types: true
    constant_identifier_names: true
    prefer_is_empty: true
    avoid_positional_boolean_parameters: true
    prefer_typing_uninitialized_variables: true
